export enum RecipeActionTypes {
  FETCH_RECIPE_LIST = '[RECIPES]_FETCH_RECIPE_LIST',
  FETCH_RECIPE = '[RECIPES]_FETCH_RECIPE',
  SELECT_RECIPE = '[RECIPE]_SELECT',
  ADD = '[RECIPES]_ADD',
  UPDATE = '[RECIPES]_UPDATE',
  RESET_SELECTED_RECIPE = '[RECIPES]_RESET_SELECTED_RECIPE'
}
