export enum ShoppingListActionTypes {
  ADD_INGREDIENT = '[SHOPPING_LIST]_ADD_INGREDIENT',
  ADD_INGREDIENTS = '[SHOPPING_LIST]_ADD_INGREDIENTS',
  UPDATE_INGREDIENT = '[SHOPPING_LIST]_UPDATE_INGREDIENT',
  DELETE_INGREDIENT = '[SHOPPING_LIST]_DELETE_INGREDIENT',
  SELECT_INGREDIENT = '[SHOPPING_LIST]_SELECT_INGREDIENT'
}
