export enum AuthActionTypes {
  LOGIN_SUCCESS = '[AUTH]_LOGIN_SUCCESS',
  LOGIN_FAILED = '[AUTH]_LOGIN_FAILED',
  SIGNUP_SUCCESS = '[AUTH]_SIGNUP_SUCCESS',
  SIGNUP_FAILED = '[AUTH]_SIGNUP_FAILED',
  LOGOUT = '[AUTH]_LOGOUT',
  SET_LOGIN_BUSY = '[AUTH]_SET_LOGIN_BUSY',
  CLEAR_LOGIN_ERROR_MESSAGE = '[AUTH]_CLEAR_LOGIN_ERROR_MESSAGE'
}
