export enum AuthActionTypes {
  LOGIN_SUCCESS = '[AUTH]_LOGIN_SUCCESS',
  LOGIN_FAILED = '[AUTH]_LOGIN_FAILED',
  SIGNUP_SUCCESS = '[AUTH]_SIGNUP_SUCCESS',
  SIGNUP_FAILED = '[AUTH]_SIGNUP_FAILED',
  AUTOLOGIN_AVAILABLE = '[AUTH]_AUTOLOGIN_AVAILABLE',
  AUTOLOGIN_NOT_AVAILABLE = '[AUTH]_AUTOLOGIN_NOT_AVAILABLE',
  LOGOUT = '[AUTH]_LOGOUT',
  SET_LOGIN_BUSY = '[AUTH]_SET_LOGIN_BUSY',
}
